language: ruby
cache: bundler

rvm:
  - 'ruby-2.2.2'

script:
  - 'bundle exec bundle-audit update && bundle exec bundle-audit check'

notifications:
  email:
    recipients:
      - jesse.whitham@gmail.com
    on_failure: change
    on_success: never
